name: 'Production Build'

on:
  workflow_run:
    workflows: ['Tests']
    branches: ['main']
    types:
      - completed

defaults:
  run:
    working-directory: ./website

jobs:
  deploy:
    name: 'Deploy'
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - name: Build Spoke
        run: npm run build -- --output-hashing=none --base-href=/spoke-vis/
      - run: npm run compodoc
      - name: Setup GitHub Pages files
        run: |
          cp dist/spoke/index.html dist/spoke/404.html
          touch dist/spoke/.nojekyll

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/dist/spoke
          commit_message: "Production deploy -- ${{ github.event.head_commit.message }}"
